//
// DO NOT MODIFY THIS FILE
//
// This file is automatically generated by the genCS.py script operating on components.xml
//

using BDG_ECS;
using System.Collections.Generic;
using String = System.String;
using Unity.Collections;
using UnityEngine;

namespace ECSteroids {
    public class Transform : BaseComponent {
        public Vector3 pos;
        public float angle;

        public void Populate(Vector3 pos, float angle) {
            this.pos = pos;
            this.angle = angle;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class Polygon : BaseComponent {
        public bool isClosed;
        public List<Vector3> points;
        public GameObject unityObject;

        public void Populate(bool isClosed, List<Vector3> points, GameObject unityObject) {
            this.isClosed = isClosed;
            this.points = points;
            this.unityObject = unityObject;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class PlayerScore : BaseComponent {
        public int score;

        public void Populate(int score) {
            this.score = score;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class BulletTag : BaseComponent {

        public void Populate() {
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class ShipTag : BaseComponent {

        public void Populate() {
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class AsteroidTag : BaseComponent {

        public void Populate() {
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class TeamId : BaseComponent {
        public int index;

        public void Populate(int index) {
            this.index = index;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class DrawColor : BaseComponent {
        public Color color;

        public void Populate(Color color) {
            this.color = color;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class AsteroidSize : BaseComponent {
        public float radius;

        public void Populate(float radius) {
            this.radius = radius;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class KeyBindings : BaseComponent {
        public List<KeyBinding> keys;

        public void Populate(List<KeyBinding> keys) {
            this.keys = keys;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class Velocity : BaseComponent {
        public Vector3 vel;

        public void Populate(Vector3 vel) {
            this.vel = vel;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class InputBuffer : BaseComponent {
        public List<KeyState> keys;
        public float steer;
        public float throttle;
        public bool isShooting;

        public void Populate(List<KeyState> keys, float steer, float throttle, bool isShooting) {
            this.keys = keys;
            this.steer = steer;
            this.throttle = throttle;
            this.isShooting = isShooting;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class ScreenLimits : BaseComponent {
        public float width;

        public void Populate(float width) {
            this.width = width;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class PointTag : BaseComponent {

        public void Populate() {
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class InputDrivesThisEntityTempTag : BaseComponent {

        public void Populate() {
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

    public class CollisionDisk : BaseComponent {
        public float radius;

        public void Populate(float radius) {
            this.radius = radius;
        }

        public override String Serialize() {
            return "";
        }

        public override bool Deserialize(String s) {
            return false;
        }

        public override void Reset() {
        }

    }

}

